// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
import Cabeçalho from "@/componentes/cabecalho";
import Rodape from "@/componentes/rodape";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html Lang="pt-br">
      <body suppressHydrationWarning={true}>
      <Cabeçalho/>
      {children}
      <Rodape/>
      </body>
    </html>
  );
}
